name: RPGChat
version: ${project.version}
api-version: ${api.version}
author: ${plugin.author}
main: dev.bermeb.rpgchat.RPGChat
softdepend: [ ChatControl ]
commands:
  rpgchat:
    description: Command for managing RPGChat